version: "3"
services:
  web:
    image: benit/buster-php-7.3 
    container_name: github-blog
    ports:
      - 8000:8000
    volumes:
      - ./:/github-blog/
    working_dir: /github-blog/
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
